import "./globals.css";

export const metadata = {
  title: "My top 10",
  description: "Generated by Trevor Brown.",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
